import { useState } from 'react'
import './App.css'

interface LetterBreakdown {
  letter: string;
  value: number;
}

interface CalculationResult {
  breakdown: LetterBreakdown[];
  letterSum: number;
  reductions: number[];
  finalNumber: number;
}

function App() {
  const [input, setInput] = useState<string>('');
  const [result, setResult] = useState<CalculationResult | null>(null);
  const [email, setEmail] = useState<string>('');
  const [sending, setSending] = useState<boolean>(false);
  const [emailSent, setEmailSent] = useState<boolean>(false);

  const getLetterValue = (letter: string): number => {
    const upper = letter.toUpperCase();
    if (upper >= 'A' && upper <= 'Z') {
      return upper.charCodeAt(0) - 64; // A=1, B=2, ..., Z=26
    }
    return 0;
  };

  const sumDigits = (num: number): number => {
    return num.toString().split('').reduce((sum: number, digit: string) => sum + parseInt(digit), 0);
  };

  const handleSubmit = () => {
    // Step 1: Convert each letter to its number and sum them
    let letterSum = 0;
    const breakdown: LetterBreakdown[] = [];
    
    for (let char of input) {
      const value = getLetterValue(char);
      if (value > 0) {
        breakdown.push({ letter: char, value });
        letterSum += value;
      }
    }

    // Step 2: Sum the digits of the result repeatedly until single digit
    let finalNumber = letterSum;
    const reductions: number[] = [letterSum];
    
    while (finalNumber >= 10) {
      finalNumber = sumDigits(finalNumber);
      reductions.push(finalNumber);
    }

    setResult({
      breakdown,
      letterSum,
      reductions,
      finalNumber
    });
    setEmailSent(false);
  };

  const handleSendEmail = () => {
    if (!email || !result) return;

    setSending(true);

    // Create email body with results
    const letterValues = result.breakdown.map(item => `${item.letter}=${item.value}`).join(', ');
    const reductionSteps = result.reductions.join(' → ');
    
    const subject = encodeURIComponent(`Letter Number Calculation Results for "${input}"`);
    const body = encodeURIComponent(
      `Letter to Number Calculator Results\n\n` +
      `Input: ${input}\n\n` +
      `Letter Values: ${letterValues}\n\n` +
      `Sum of Letter Values: ${result.letterSum}\n\n` +
      `${result.reductions.length > 1 ? `Digit Reduction: ${reductionSteps}\n\n` : ''}` +
      `Final Number: ${result.finalNumber}\n\n` +
      `---\n` +
      `Generated by Letter to Number Calculator`
    );

    // Open default email client
    window.location.href = `mailto:${email}?subject=${subject}&body=${body}`;

    setTimeout(() => {
      setSending(false);
      setEmailSent(true);
    }, 1000);
  };

  return (
    <>
      <link 
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" 
        rel="stylesheet"
      />
      
      <div className="min-vh-100 bg-light py-5">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <div className="card shadow-lg">
                <div className="card-body p-4 p-md-5">
                  <h1 className="card-title text-center mb-4 fw-bold text-primary">
                    Letter to Number Calculator
                  </h1>
                  
                  <div className="mb-4">
                    <label className="form-label fw-semibold">
                      Enter a word or phrase:
                    </label>
                    <input
                      type="text"
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyPress={(e) => e.key === 'Enter' && handleSubmit()}
                      className="form-control form-control-lg"
                      placeholder="Type something..."
                    />
                  </div>
                  
                  <button
                    onClick={handleSubmit}
                    className="btn btn-primary btn-lg w-100 mb-4"
                  >
                    Calculate
                  </button>

                  {result && (
                    <div>
                      <div className="card bg-light mb-3">
                        <div className="card-body">
                          <h5 className="card-title fw-semibold mb-3">
                            Letter Values:
                          </h5>
                          <div className="d-flex flex-wrap gap-2">
                            {result.breakdown.map((item, idx) => (
                              <span
                                key={idx}
                                className="badge bg-primary fs-6 px-3 py-2"
                              >
                                {item.letter} = {item.value}
                              </span>
                            ))}
                          </div>
                        </div>
                      </div>

                      <div className="card bg-info bg-opacity-10 mb-3">
                        <div className="card-body">
                          <h5 className="card-title fw-semibold mb-2">
                            Sum of Letter Values:
                          </h5>
                          <p className="display-6 fw-bold text-primary mb-0">
                            {result.letterSum}
                          </p>
                        </div>
                      </div>

                      {result.reductions.length > 1 && (
                        <div className="card bg-secondary bg-opacity-10 mb-3">
                          <div className="card-body">
                            <h5 className="card-title fw-semibold mb-2">
                              Digit Reduction:
                            </h5>
                            <p className="mb-0 fs-5">
                              {result.reductions.join(' → ')}
                            </p>
                          </div>
                        </div>
                      )}

                      <div className="card bg-primary text-white mb-4">
                        <div className="card-body text-center py-4">
                          <h5 className="card-title fw-semibold mb-3">
                            Final Number:
                          </h5>
                          <p className="display-1 fw-bold mb-0">
                            {result.finalNumber}
                          </p>
                        </div>
                      </div>

                      {/* Email Section */}
                    </div>
                  )}
                </div>
              </div>

              <div className="text-center mt-4 text-muted">
                <small>A=1, B=2, C=3, ... Z=26</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default App
